# Generated by Django 5.1.4 on 2024-12-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0002_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
