# Generated by Django 5.1.4 on 2025-01-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0004_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
