# Generated by Django 5.1.4 on 2025-01-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0009_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='is_match',
            field=models.BooleanField(default=False),
        ),
    ]
