# Generated by Django 5.1.4 on 2025-01-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0013_remove_chatmessage_receiver_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
