# Generated by Django 5.1.4 on 2025-01-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0017_alter_chatroom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
